import { StoreProvider } from './StoreProvider'

import type { Metadata } from 'next'
import '@/app/globals.css'
import ThemeProvider from '@/app/components/ThemeProvider'
import MainNav from '@/app/components/MainNav'
import Link from 'next/link'
import DarkModeBtn from '@/app/components/DarkModeBtn'
import Sun from '@/app/components/svg_icons/Sun'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface ReactChildren {
  readonly children: React.ReactNode
}

export default function RootLayout({ children }: ReactChildren) {
  return (
    <StoreProvider>
      <html lang="en">
        <ThemeProvider>
          <div>
            <header className="flex p-5 justify-center w-full">
              <div className="flex w-full max-w-[900]">
                <div className="flex-auto">
                  <Link href={'/'}>Will Hausman</Link>
                </div>
                <MainNav />
                <div className="flex flex-auto justify-end">
                  <DarkModeBtn />
                  {/* <Boop boopConfig={{ scale: 1.5 }}>
                  <Sun />
                </Boop> */}
                </div>
              </div>
            </header>

            <div className="flex justify-center">{children}</div>
          </div>
        </ThemeProvider>
      </html>
    </StoreProvider>
  )
}
